# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/kmgrytte/thespinnerdood/thespinnerdood.cache/wt [current_project]
set_property parent.project_path C:/Users/kmgrytte/thespinnerdood/thespinnerdood.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/kmgrytte/thespinnerdood/thespinnerdood.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  M:/pc/Dokumenter/lab3update/ru.vhd
  M:/pc/Dokumenter/lab3update/cu.vhd
  M:/pc/Dokumenter/lab3update/p_ctrl.vhd
  M:/pc/Dokumenter/lab3update/pos_meas.vhd
  M:/pc/Dokumenter/lab3update/seg7ctrl.vhd
  M:/pc/Dokumenter/lab3update/pos_ctrl.vhd
  M:/pc/Dokumenter/lab3update/cru.vhd
  M:/pc/Dokumenter/lab3update/pos_seg7_ctrl_ent.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/kmgrytte/thespinnerdood/thespinnerdood.srcs/constrs_1/new/letitrip.xdc
set_property used_in_implementation false [get_files C:/Users/kmgrytte/thespinnerdood/thespinnerdood.srcs/constrs_1/new/letitrip.xdc]


synth_design -top pos_seg7_ctrl -part xc7z020clg484-1


write_checkpoint -force -noxdef pos_seg7_ctrl.dcp

catch { report_utilization -file pos_seg7_ctrl_utilization_synth.rpt -pb pos_seg7_ctrl_utilization_synth.pb }
